version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - brk-network

  # Backend service  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB=brk_sneakers
      - DEBUG=True
    networks:
      - brk-network

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongodb/seed_init.js:/docker-entrypoint-initdb.d/seed_init.js:ro
    networks:
      - brk-network

networks:
  brk-network:
    driver: bridge

volumes:
  mongo-data:
    